---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/pthornton/guestbook
        targetRevision: HEAD
        path: helm
      destination:
        server: '{{server}}'
        namespace: guestbook
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
