---
# Source: helm-guestbook/templates/Application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: https://github.com/pthornton/guestbook
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

